name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Change to '21' if your project supports it
          distribution: 'temurin'
          cache: maven
          server-id: github  # Must match <id> in settings.xml
          settings-path: ${{ github.workspace }}  # Generates settings.xml automatically

      - name: Build with Maven (Skip Tests for Speed)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
